### ISSUE TITLE
rt_weekly tests not exercised?

### ISSUE THREAD

**Issue by climbfuji** [ufs-community/ufs-weather-model#1933]
## Description
At least one of the `rt_weekly.conf` tests is not exercised it seems, because it is broken. On Hera  with Intel:
```
> ./rt.sh -e -l rt_weekly.conf -n control_c768 intel -k 2>&1 | tee rt_control_c768.log
...

> cat /scratch1/NCEPDEV/stmp2/Dom.Heinzeller/FV3_RT/rt_3830/compile_1_intel/err
...
Found Python: /scratch1/NCEPDEV/jcsda/jedipara/spack-stack/miniconda-3.9.12/bin/python3.9
Calling CCPP code generator (ccpp_prebuild.py) for suites --suites=FV3_GFS_v16,FV3_GFS_v16_nsstNoahmpUGWPv1 ...
CMake Error at FV3/ccpp/CMakeLists.txt:40 (message):
  An error occured while running ccpp_prebuild.py, check
  /scratch1/NCEPDEV/stmp2/Dom.Heinzeller/FV3_RT/rt_3830/compile_1_intel/build_fv3_1_intel/FV3/ccpp/ccpp_prebuild.{out,err}

> cat /scratch1/NCEPDEV/stmp2/Dom.Heinzeller/FV3_RT/rt_3830/compile_1_intel/build_fv3_1_intel/FV3/ccpp/ccpp_prebuild.err
INFO: Logging level set to INFO
INFO: Found TYPEDEFS_NEW_METADATA dictionary in config, assume at least some data is in new metadata format
INFO: Parsing suite definition files ...
INFO: Parsing suite definition file suites/suite_FV3_GFS_v16.xml ...
INFO: Parsing suite definition file suites/suite_FV3_GFS_v16_nsstNoahmpUGWPv1.xml ...
CRITICAL: Suite definition file suites/suite_FV3_GFS_v16_nsstNoahmpUGWPv1.xml not found.
ERROR: Parsing suite definition file suite_FV3_GFS_v16_nsstNoahmpUGWPv1.xml failed.
Traceback (most recent call last):
  File "/scratch1/NCEPDEV/jcsda/dom.heinzeller/ufs-weather-model-testing/ufs-weather-model/FV3/ccpp/framework/scripts/ccpp_prebuild.py", line 813, in <module>
    main()
  File "/scratch1/NCEPDEV/jcsda/dom.heinzeller/ufs-weather-model-testing/ufs-weather-model/FV3/ccpp/framework/scripts/ccpp_prebuild.py", line 723, in main
    raise Exception('Parsing suite definition files failed.')
Exception: Parsing suite definition files failed.
```
This does not seem to be site/compiler/software-env dependent. If these tests are not run, what's the merit of keeping them in the repo?

### To Reproduce:
See description

## Additional context
n/a

**Comment by climbfuji** [comment]
Related, is there any test or otherwise available config that runs at C768 operational resolution, preferably with the latest GFSv17 prototype configuration? Thanks!

**Comment by JessicaMeixner-NOAA** [comment]
@climbfuji I provided @jkbk2004 a canned case of HR2, but I'm not sure if that has made its way back into a weekly test or not.  We can run from the workflow for the latest C768 prototype testing, although the workflow is not yet up to date with the latest ufs-weather-model develop branch (it's work in progress to update this and get past various module issues).

**Comment by climbfuji** [comment]
> @climbfuji I provided @jkbk2004 a canned case of HR2, but I'm not sure if that has made its way back into a weekly test or not. We can run from the workflow for the latest C768 prototype testing, although the workflow is not yet up to date with the latest ufs-weather-model develop branch (it's work in progress to update this and get past various module issues).

That wouldn't be a problem. I am looking for a canned test case that I can take (without having to learn global workflow) and experiment with threading, block sizes in FV3ATM etc.

**Comment by JessicaMeixner-NOAA** [comment]
@climbfuji  Canned case is here: 
/scratch1/NCEPDEV/climate/Jessica.Meixner/HR2cannedcase
If you copy this whole folder and then modify the jobcard.sub to an account you have access to, you should just simply be able to submit and everything will run.

**Comment by climbfuji** [comment]
> @climbfuji Canned case is here: /scratch1/NCEPDEV/climate/Jessica.Meixner/HR2cannedcase If you copy this whole folder and then modify the jobcard.sub to an account you have access to, you should just simply be able to submit and everything will run.

This is awesome, thanks very much @JessicaMeixner-NOAA !

**Comment by climbfuji** [comment]
I should have asked for the corresponding hash and correct compile command for the ufs-weather-model ... doing that now :-)

**Comment by JessicaMeixner-NOAA** [comment]
ufs-weather-model tag is: https://github.com/ufs-community/ufs-weather-model/tree/GFSv17.HR2 
Build script is here: https://github.com/NOAA-EMC/global-workflow/blob/prototype/hr2/sorc/build_ufs.sh 
I believe the settings you need to know are: 
-DAPP=S2SWA -D32BIT=ON -DCCPP_SUITES="FV3_GFS_v17_p8,FV3_GFS_v17_coupled_p8" 

Let me know if I left something important out.

**Comment by climbfuji** [comment]
Thanks, I am trying that now.

**Comment by zach1221** [comment]
Hello, @climbfuji . Do you need any additional assistance here?

**Comment by climbfuji** [comment]
No, I was able to use what @JessicaMeixner-NOAA sent me - but the original issue that `rt_weekly` tests are not exercised remains (which is outside my responsibilities).

**Comment by zach1221** [comment]
> ./rt.sh -e -l rt_weekly.conf -n control_c768 intel -k 2>&1 | tee rt_control_c768.log

Ok, thanks for clarifying. I can look into the issue.

**Comment by zach1221** [comment]
Will follow up in PI12 to address this issue.

**Comment by gspetro-NOAA** [comment]
It looks like PR #2749 will update the control_c768 configuration to work. I will work on a PR to update rt_weekly.conf to run on Ursa and Derecho; it currently runs only on Hera and Jet, which are/will be deprecated.

**Comment by dpsarmie** [comment]
@gspetro-NOAA, I agree, we can close this and continue discussions in https://github.com/ufs-community/ufs-weather-model/pull/2749 and https://github.com/ufs-community/ufs-weather-model/issues/2748
