### ISSUE TITLE
RT tests are not working with -e flag on Hercules

### ISSUE THREAD

**Issue by uturuncoglu** [ufs-community/ufs-weather-model#2334]
## Description
I am getting Python module error when I try to run the RTs with -e option (ecflow).

### To Reproduce:
What compilers/machines are you seeing this with? Intel
Give explicit steps to reproduce the behavior.
1.  git clone --recursive https://github.com/ufs-community/ufs-weather-model.git ufs-weather-model_dev
2. cd ufs-weather-model_dev/tests
3. ./rt.sh -a nems -e

## Additional context
N/A

## Output
**output logs**

```
rt_utils.sh: Starting ECFLOW tasks...
rt_utils.sh: Total number of tasks processed -- 303

ECFLOW Tasks Remaining: 303/303 Traceback (most recent call last):
  File "/work2/noaa/nems/tufuk/COASTAL/ufs-weather-model_dev/tests/abort_dep_tasks.py", line 3, in <module>
    import ecflow as ecflow
  File "/work/noaa/epic/role-epic/spack-stack/hercules/ecflow-5.8.4/lib/python3.9/site-packages/ecflow/__init__.py", line 1, in <module>
    from .ecflow import *
SystemError: type Boost.Python.enum has the Py_TPFLAGS_HAVE_GC flag but has no traverse function
```

**Comment by BrianCurtis-NOAA** [comment]
@RatkoVasic-NOAA @jkbk2004 have we tested on Orion with -e ? If so, is the ecflow package built with the python support on Orion? Maybe there's some permission issue somewhere?

**Comment by RatkoVasic-NOAA** [comment]
Yes, it is working on Orion. I just ran full rt.sh using -e option.
Here is path for Orion ecflow:
/work/noaa/epic/role-epic/spack-stack/orion/modulefiles/

**Comment by BrianCurtis-NOAA** [comment]
@RatkoVasic-NOAA Is there a PR with orion changes coming that @uturuncoglu could pull and use?

**Comment by RatkoVasic-NOAA** [comment]
#2332 is issue. I'll create new PR today. If cannot wait (it can take some time for commit), here is my branch: https://github.com/RatkoVasic-NOAA/ufs-weather-model/tree/orion-rocky9

**Comment by uturuncoglu** [comment]
@RatkoVasic-NOAA @BrianCurtis-NOAA Thanks all for your help. JFYI, the fix is not urgent for me at this point. I had this error when I sync UFS Coastal model with head of develop. So, I just want to inform you about that. Thanks again.

**Comment by gspetro-NOAA** [comment]
@uturuncoglu @RatkoVasic-NOAA Has this issue been resolved (or become obsolete)? Or is it just waiting for someone to work it?

**Comment by uturuncoglu** [comment]
@gspetro-NOAA I did not test it recently.

**Comment by gspetro-NOAA** [comment]
@uturuncoglu I ran the control_c48 intel RT on Hercules with ecFlow with no trouble. Then I ran the entire RT suite on Hercules with no issues. It seems that whatever the issue was has been resolved. If you come across it again, feel free to open a new issue.

**Comment by uturuncoglu** [comment]
@gspetro-NOAA Thank you!
