### ISSUE TITLE
ecflow failure on hercules

### ISSUE THREAD

**Issue by jkbk2004** [ufs-community/ufs-weather-model#2454]
## Description

ECFLOW Tasks Remaining: 303/303 Traceback (most recent call last):
  File "/work/noaa/epic/jongkim/UFS-RT/hercules/rt-2146/tests/abort_dep_tasks.py", line 3, in <module>
    import ecflow as ecflow
  File "/work/noaa/epic/role-epic/spack-stack/hercules/ecflow-5.8.4/lib/python3.9/site-packages/ecflow/__init__.py", line 1, in <module>
    from .ecflow import *
SystemError: type Boost.Python.enum has the Py_TPFLAGS_HAVE_GC flag but has no traverse function
rt.sh finished

### To Reproduce:

run rt.sh with -e on hercules. 

## Additional context

It may need to re-install ecflow lib on hercules.

## Output

ECFLOW Tasks Remaining: 303/303 Traceback (most recent call last):
  File "/work/noaa/epic/jongkim/UFS-RT/hercules/rt-2146/tests/abort_dep_tasks.py", line 3, in <module>
    import ecflow as ecflow
  File "/work/noaa/epic/role-epic/spack-stack/hercules/ecflow-5.8.4/lib/python3.9/site-packages/ecflow/__init__.py", line 1, in <module>
    from .ecflow import *
SystemError: type Boost.Python.enum has the Py_TPFLAGS_HAVE_GC flag but has no traverse function
rt.sh finished
rt.sh: Cleaning up...

**Comment by gspetro-NOAA** [comment]
@jkbk2004 I ran the control_c48 intel RT on Hercules with ecFlow with no trouble. Then I ran the entire RT suite on Hercules with no issues. It seems that whatever the issue was has been resolved. I'll close this, and if we come across it again, we can open a new issue.
